In [1]:
import numpy as np
#匯入nimpy，用於處理數值運算和陣列操作。
M = np.array([[0, 2, 1, 1, 1, 1, 1, 2, 1, 3],
              [2, 0, 1, 1, 1, 0, 0, 1, 1, 2],
              [1, 1, 0, 1, 1, 0, 0, 0, 0, 1],
              [1, 1, 1, 0, 1, 0, 0, 0, 0, 1],
              [1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
              [1, 0, 0, 0, 0, 0, 1, 1, 0, 1],
              [1, 0, 0, 0, 0, 1, 0, 1, 0, 1],
              [2, 1, 0, 0, 0, 1, 1, 0, 1, 2],
              [1, 1, 0, 0, 0, 0, 0, 1, 0, 1],
              [3, 2, 1, 1, 1, 1, 1, 2, 1, 0]])
#定義矩陣M。
def pmi(M, positive=True):
#定義計算互訊的函數pmi。
    col_totals = M.sum(axis=0)
    #計算每一列的總和
    row_totals = M.sum(axis=1)
    #計算每一行的總和
    total = col_totals.sum()
    #計算所有元素的總和
    expected = np.outer(row_totals, col_totals) / total
    #計算期望共現矩陣，表示如果詞在文件中是獨立的，它們的共現次數會是多少。
    M = M / expected
    # Silence distracting warnings about log(0):
    with np.errstate(divide='ignore'):
    #忽略除以零的警告。
        M = np.log(M)
        #對上述比率取自然對數，得到點間互訊矩陣。
    M[np.isinf(M)] = 0.0  # log(0) = 0
    if positive:
        M[M < 0] = 0.0
    return M

M_pmi = pmi(M)
#使用剛定義的pmi函數計算點間互訊矩陣。
np.set_printoptions(precision=2)
#設置NumPy的列印選項，以控制浮點數的小數位數。
print(M_pmi)
#列印計算出的點間互訊矩陣。

[[0.   0.18 0.07 0.07 0.07 0.3  0.3  0.3  0.3  0.22]
 [0.18 0.   0.44 0.44 0.44 0.   0.   0.   0.66 0.18]
 [0.07 0.44 0.   1.03 1.03 0.   0.   0.   0.   0.07]
 [0.07 0.44 1.03 0.   1.03 0.   0.   0.   0.   0.07]
 [0.07 0.44 1.03 1.03 0.   0.   0.   0.   0.   0.07]
 [0.3  0.   0.   0.   0.   0.   1.48 0.78 0.   0.3 ]
 [0.3  0.   0.   0.   0.   1.48 0.   0.78 0.   0.3 ]
 [0.3  0.   0.   0.   0.   0.78 0.78 0.   0.78 0.3 ]
 [0.3  0.66 0.   0.   0.   0.   0.   0.78 0.   0.3 ]
 [0.22 0.18 0.07 0.07 0.07 0.3  0.3  0.3  0.3  0.  ]]
